### ISSUE TITLE
feat: remember more settings  for zero-config

### ISSUE THREAD

**Issue by FredrikMWold** [ieedan/jsrepo#284]
### Describe the feature

Is it possible for the CLI to remember when I’ve confirmed the absence of jsrepi.json and granted permission to download from the same registry? It would make the process less repetitive and more efficient.

### Validations

- [X] I have checked other issues to see if my feature was already requested or added

**Comment by ieedan** [comment]
You can skip the confirmation prompt with the `--y` flag

**Comment by FredrikMWold** [comment]
@ieedan Seems like --allow works but not --yes or -y
![Peek 2024-12-13 01-46](https://github.com/user-attachments/assets/49ec6035-8573-4834-9a65-b9831ca12205)

**Comment by ieedan** [comment]
> @ieedan Seems like --allow works but not --yes or -y
> 
> ![Peek 2024-12-13 01-46](https://github.com/user-attachments/assets/49ec6035-8573-4834-9a65-b9831ca12205)
> 
> 

Good catch I'll look into this in the morning!

**Comment by ieedan** [comment]
@FredrikMWold fixes this in #287
