### ISSUE TITLE
feat: add block list picker when using zero-config

### ISSUE THREAD

**Issue by FredrikMWold** [ieedan/jsrepo#285]
### Describe the feature

When running `npx jsrepo add github/<owner>/<name>/<category>/<name>` in zero-config mode, could it display the same list of blocks the same way as with a config file? 

### Validations

- [X] I have checked other issues to see if my feature was already requested or added

**Comment by ieedan** [comment]
It already does just do

```
npx jsrepo add --repo github/ieedan/std
```
