### ISSUE TITLE
feat: re-usable scripts / CLI tools

### ISSUE THREAD

**Issue by negue** [ieedan/jsrepo#315]
### Describe the feature

I just had this idea, I wanted to share 😬 

what if we could also have blocks that are scripts which we could triggered by the jsrepo cli as well, instead of adding a block and adding a package script for it, unless jsrepo could add the script entry automagically as well?

otherwise, something like:

`jsrepo exec category/block ARGS`

or 

`jsrepo exec repo/category/block` so that it doesn't need to be downloaded (just throwing ideas in the room 😬 )

or  even just by `jsrepo exec` which lists all possible ones

I couldn't find any other issues/features yet, if there were I'm sorry

### Validations

- [X] I have checked other issues to see if my feature was already requested or added

**Comment by ieedan** [comment]
This is interesting I hadn't thought about this before.

There definitely could be some utility in this.

I think we could just make it so you could run any .js / .ts file. 

We do have to use something like tsx under the hood though.

Curious if anyone else has thought of this and what some common use cases might be!

**Comment by negue** [comment]
My current "usecases" (well me soon wanting to try out, don't have any scripts yet) would be:

- https://google.github.io/zx/ scripts for all kinds of stuff
- using ts-morph some kind of "move type into a different file" automatic refactor, so that I don't do it manually 😬 

there will be probably more down the road

Looking forward if others also think about something like this ^^

**Comment by ieedan** [comment]
Also as far as I know there's no way to not download the code onto your computer before running it.

Even stuff like npx has to first download the code before running it.

It would probably just go to an invisible temp directory where it could be deleted afterwards.

**Comment by ieedan** [comment]
I think this is cool so I have a PR #317 open to add it. Let me know what you think of this API!

**Comment by negue** [comment]
Oh awesome!! - gonna test it in a few, thank you 🎉
