### ISSUE TITLE
feat: Forced Dependencies Per Category

### ISSUE THREAD

**Issue by FredrikMWold** [ieedan/jsrepo#316]
### What’s the Idea?  
Add a way to force certain dependencies that cant be auto detected for specific categories in `jsrepo`. This would make it easier to manage shared resources.

### Why This is Useful  
I want to have one `jsrepo` registry per client, with each registry containing components tailored to the client’s styling and way of doing things. Each client typically has a global CSS file that all components in their registry rely on.  

Currently, `jsrepo` doesn’t auto-detect CSS dependencies, so I have to handle this manually. It would save time and improve the workflow if `jsrepo` could automatically include these files during the build process.

### How It Could Work  
Add a `forcedDeps` option to the `jsrepo-build-config` file, like this:  

```javascript
forcedDeps: {
    "category1": ["path/to/global.css", "path/to/global.js"],
    "category2": ["path/to/another-dependency.js"]
}


### Validations

- [X] I have checked other issues to see if my feature was already requested or added

**Comment by ieedan** [comment]
This kinda fits more along the lines of shared configuration.

I haven't quite figured out a nice way to do this I don't necessarily think this forced deps api is the right way to go.

Right now you kinda have 2 options:
- document the need for configuration files
- add a side effect import on each component like 
```ts
import '../styles/global.css';
```

Configuration is something that would be nice to solve but it has a lot of challenges to make it work for everyone.

**Comment by FredrikMWold** [comment]
Got it, I can see how this seems like part of a larger issue.  

Looks like option 3 it is, manually adding them to the manifest file for now! 😆
